PKGDIR=../..
<$PKGDIR/mkconfig


DIRS=\
	t\

<$MKFILES/mksubdirs


DISBIN=$PKGDIR/dis/cmd

TARG=\
	register.dis\

SYSMODULES=\
	sys.m\
	draw.m\
	arg.m\
	registries.m\

OPTMODULES=\
	opt/powerman/logger/module/logger.m\

MODULES=\

<$MKFILES/mkdis
